apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.centurylinklabs.watchtower.enable: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: celery-scheduler
  name: celery-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        com.centurylinklabs.watchtower.enable: "true"
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: celery-scheduler
    spec:
      containers:
        - command:
            - /app/entrypoint-celery.sh
          env:
            - name: CELERY_BEAT
              value: "1"
            - name: CELERY_BEAT_SEPARATELY
              value: "1"
            - name: DATABASE_URL
              value: sqlite:////nefarious-db/db.sqlite3
            - name: HOST_DOWNLOAD_PATH
              value: /tmp
            - name: INTERNAL_DOWNLOAD_PATH
              value: /downloads
            - name: REDIS_HOST
              value: redis
          image: lardbit/nefarious
          name: celery-scheduler
          volumeMounts:
            - mountPath: /nefarious-db
              name: nefarious-db
      restartPolicy: Always
      volumes:
        - name: nefarious-db
          persistentVolumeClaim:
            claimName: nefarious-db
