apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media-server"
  labels:
    io.kompose.service: jackett-config
  name: jackett-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
