apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "media-server"
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jackett
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: jackett
    spec:
      containers:
        - image: linuxserver/jackett
          name: jackett
          ports:
            - containerPort: 9117
              protocol: TCP
          resources:
            limits:
              memory: "209715200"
          volumeMounts:
            - mountPath: /config
              name: jackett-config
      restartPolicy: Always
      volumes:
        - name: jackett-config
          persistentVolumeClaim:
            claimName: jackett-config
