apiVersion: v1
kind: Service
metadata:
  namespace: "media-server"
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nefarious
  name: nefarious
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
    type: ClusterIP  
  selector:
    io.kompose.service: nefarious
