apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media-server"
  labels:
    io.kompose.service: nefarious-db
  name: nefarious-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
