apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.centurylinklabs.watchtower.enable: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        com.centurylinklabs.watchtower.enable: "true"
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: linuxserver/transmission
          name: transmission
          ports:
            - containerPort: 9091
              protocol: TCP
            - containerPort: 51413
              protocol: TCP
          volumeMounts:
            - mountPath: /config/settings.json
              name: transmission-cm1
              readOnly: true
              subPath: settings.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: transmission-settings.json
                path: settings.json
            name: transmission-cm1
          name: transmission-cm1
