apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "media-server"
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: linuxserver/transmission
          name: transmission
          ports:
            - containerPort: 9091
              protocol: TCP
            - containerPort: 51413
              protocol: TCP
          volumeMounts:
          - mountPath: /downloads
            name: download-volume
          - mountPath: /config/settings.json
            subPath: settings.json
            name: config-volume
            readOnly: true
      restartPolicy: Always
      volumes:
      - name: download-volume
        persistentVolumeClaim:
          claimName: transmission-pvc
      - name: config-volume
        configMap:
          name: transmission-config
          items:
          - key: transmission-settings.json
            path: settings.json
