apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: watchtower
  name: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: watchtower
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: watchtower
    spec:
      containers:
        - args:
            - --label-enable
            - --cleanup
          env:
            - name: WATCHTOWER_POLL_INTERVAL
              value: "3600"
          image: containrrr/watchtower
          name: watchtower
      restartPolicy: Always
